better json formatting
psibi/cricbuzz pull request #6
Opened 2017-03-28 16:34 UTC by vozille

2017-03-28 21:34 UTC, psibi requested changes

2017-03-28 21:34 UTC, psibi commented on data.json
> +    "SLU23 vs AFG": {
Does this file have to be commited ?

2017-03-29 02:18 UTC, vozille commented
Oh sorry, I added that file just to show the results.. there's no need to

On 29-Mar-2017 3:04 AM, "Sibi" <notifications@github.com> wrote:

> *@psibi* requested changes on this pull request.
> ------------------------------
>
> In data.json
> <https://github.com/psibi/cricbuzz/pull/6#discussion_r108542520>:
>
> > @@ -0,0 +1,194 @@
> +{
> +    "SLU23 vs AFG": {
>
> Does this file have to be commited ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/psibi/cricbuzz/pull/6#pullrequestreview-29580786>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AI4oCsoITUnHsLy_6TYfAM1qpLj2PfcQks5rqXz1gaJpZM4Mr4Wk>
> .
>

2017-03-30 05:02 UTC, merged

2017-03-30 05:02 UTC, psibi commented
Thanks!